# Generated by Django 4.0.4 on 2022-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiseloadas', '0002_alter_kisealoadas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisealoadas',
            name='leiras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='leírás'),
        ),
    ]
