# Generated by Django 4.0.4 on 2022-04-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiseloadas', '0003_kisealoadas_leiras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisealoadas',
            name='leiras',
        ),
    ]
